jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://admin:admin123@localhost:5432/db

spring:
  security:
    oauth2:
      resource:
        filter-order: 3
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dll-auto: create
  h2:
    console:
      path: /h2-console
      enabled: true

server:
  servlet:
    context-path: /api

security:
  jwt:
    key-store: classpath:mykeystore.jks
    key-store-password: changeme
    key-pair-alias: servercert
    key-pair-password: letmein
    public-key: classpath:public.txt